076 Project Page Component
UoaWDCC/younite-web pull request #97
Opened 2024-08-06 13:16 UTC by panmann7

## Context
Matching the project page design to what is shown on Figma. 

Closes #76 

## What Changed?
Fixed the CSS styling of the project page component. 

## How To Review
To view, go to next\app\projects\page.tsx

## Notes

2024-08-07 00:55 UTC, Oculux314 requested changes
Nice, like the alt text addition 👍 

Something I remember Yvonne wanted was having all the text line up towards the middle like this:
![image](https://github.com/user-attachments/assets/2a6785eb-5d2d-4789-acfe-41e444ed0eb2)
(at the moment the text is crushed to the right if there isn't enough of it)
![image](https://github.com/user-attachments/assets/82440c22-9b6b-471b-bd83-f75091bfa41c)

Also! Might be impossible, just msg here if so, but would it be possible to make this text extrabold? (You may need to edit tailwind.config.js)
![image](https://github.com/user-attachments/assets/4df745cc-ef53-4505-bd9a-bcef00474fca)

2024-08-07 00:57 UTC, Oculux314 commented on next/app/projects/page.tsx
> +          className="absolute inset-0 -z-10 object-cover object-[center_bottom] w-full h-full brightness-50"
P.s.! Is there a reason you chose to bottom-align images? Not right or wrong just curious~~

2024-08-07 10:52 UTC, YvonneLiew requested changes
Yeah I agree with what Nate said above with regards to the centering of the text. Can you make it so that if there's little text, it's more centred?

2024-08-23 01:18 UTC, Oculux314 commented
@panmann7 Sorry this is great work but since the Projects page is being redone I'm going to close this PR! Look forward to seeing your work with the projects images :D

2024-08-23 01:18 UTC, closed without merging